version: '2.2'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tpachato
      MYSQL_USER: jalel
      MYSQL_PASSWORD: jalel
    ports:
      - 3377:3306

  app:
    build: ./
    restart: on-failure
    ports:
      - 8900:8089
    depends_on:
      - mysqldb
