version: '3'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: youssefdb   
    ports:
      - 3306:3306
    networks:
     - projectdevops
     
  spring-boot:
    image: youssefselmi/achatproject:1.0
    container_name: springcontainer
    ports:
      - 8089:8089
    depends_on:
      - database
    networks:
      - projectdevops 
    restart: on-failure  
    
     
networks:
  projectdevops: